name: Deploy to NCP

on:
  push:
    branches: [ main ] # 메인 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Public 서버 접속 및 배포
        uses: appleboy/ssh-action@master
        with:
          host: 49.50.139.42
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }} # GitHub Secrets에 등록할 이름
          script: |
            # 1. Public 서버 (React) 업데이트
            cd /var/www/html/react_project
            git pull
            npm install
            npm run build
            systemctl restart nginx

            # 2. Private 서버 (Node.js) 업데이트 연쇄 실행
            ssh root@10.1.2.7 "cd /home/node_project && git pull && npm install && pm2 restart server.js"